---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 17
      start_hour = 18
      end_hour = 19
      blacklisted_namespaces = ["kube-system", "prod"]
      graceperiod_sec= 10
      [debug]
      enabled= true
      schedule_immediate_kill= true