---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 12
      start_hour = 13
      end_hour = 14
      time_zone = "America/New_York"  
      blacklisted_namespaces = ["kube-system", "prod"]