logging:
  level:
    .: error
    org.springframework: ERROR
    springml.customer: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
---
spring:
  profiles: dev
mysqldb:
  project: springmlproject
  instance: customer
  database: customer_master
  region: us-east1
  user: ${CLOUD_SQL_DEV_DB_USER}
  password: ${CLOUD_SQL_DEV_DB_PASSWORD}

--- 
spring:
  profiles: test
mysqldb:
  project: springmlproject
  instance: customer
  database: customer_master
  region: us-east1
  user: ${CLOUD_SQL_TEST_DB_USER}
  password: ${CLOUD_SQL_TEST_DB_PASSWORD}
